<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $foods = [
            [
                'image' => 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/0346a29a89ef229b1a0ff9697184f944/Derivates/cb5051204f4a4525c8b013c16418ae2904e737b7.jpg',
                'name' => 'Spaghetti alla carbonara',
                'ingredients' => 'Spaghetti, Tuorli, Guanciale, Pecorino romano, Pepe Nero',
                'description' => "Dove sono nati gli spaghetti alla carbonara? Il Vicolo della Scrofa, per chi conosce Roma, è una delle stradine più caratteristiche e ricche di simboli. Proprio in una trattoria di questa strada, da cui il nome del vicolo, pare sia stata realizzata la prima carbonara, nel 1944. La storia più attendibile su questo primo piatto, infatti, racconta l'incontro tra gli ingredienti a disposizione dei soldati americani e la fantasia di un cuoco romano.",
                'price' => '11€',
                'visible' => true,
                'user_id' => 5,

            ],
            [
                'image' => 'https://www.giallozafferano.it/images/ricette/219/21989/foto_hd/hd650x433_wm.jpg',
                'name' => 'Spaghetti cacio e pepe',
                'ingredients' => 'Spaghetti, Pepe nero, Pecorino romano',
                'description' => "Gli spaghetti cacio e pepe sono diventati oramai piatti simbolo dell'italianità, realizzati con ingredienti DOP legati alle tradizioni dei territori in cui sono nate.",
                'price' => '8€',
                'visible' => true,
                'user_id' => 5,

            ],
            [
                "image" => "https://www.buttalapasta.it/wp-content/uploads/2023/08/Risotto-ai-funghi-porcini-25082023-buttalapasta.it_.jpg",
                "name" => "Risotto ai Funghi Porcini",
                "ingredients" => "Riso Arborio, funghi porcini freschi, cipolla, brodo di carne, vino bianco, burro, parmigiano reggiano",
                "description" => "Il risotto ai funghi porcini è un piatto italiano elegante e saporito, preparato con riso Arborio cotto lentamente in brodo di carne e arricchito con funghi porcini freschi, cipolla, vino bianco, burro e parmigiano reggiano. È cremoso e ricco di sapore.",
                "price" => "14.50€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.ricettedellanonna.net/wp-content/uploads/2014/09/lasagne-al-ragu%CC%80.jpg",
                "name" => "Lasagna alla Bolognese",
                "ingredients" => "Fogli di pasta, ragù di carne, besciamella, parmigiano reggiano",
                "description" => "La lasagna alla bolognese è un piatto italiano classico, composto da strati di pasta intercalati con ragù di carne, besciamella e parmigiano reggiano. È un piatto ricco e gratificante.",
                "price" => "14.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.conad.it/assets/images/ricette/dayone-ricette/s-d/s-d-risottomilanese.jpg?_u=9fec060990adfc958e77ee3f46a9eb3b7af109eb",
                "name" => "Risotto alla Milanese",
                "ingredients" => "Riso carnaroli, zafferano, brodo di carne, cipolla, vino bianco, burro",
                "description" => "Il risotto alla milanese è un piatto lombardo famoso per il suo colore giallo intenso dovuto allo zafferano. È preparato con riso carnaroli cotto in brodo di carne, cipolla, vino bianco, burro e zafferano. È cremoso e aromatico.",
                "price" => "11.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://media-assets.lacucinaitaliana.it/photos/635169cdbc2c8a8e10d1f342/16:9/w_2560%2Cc_limit/GettyImages-482478191.jpg",
                "name" => "Ossobuco alla Milanese",
                "ingredients" => "Fette di vitello, osso con midollo, vino bianco, brodo di carne, cipolla, sedano, carota",
                "description" => "L'ossobuco alla milanese è un piatto tradizionale lombardo, composto da fette di vitello con osso e midollo, brasate lentamente in un sugo a base di vino bianco, brodo di carne, cipolla, sedano e carota. È succulento e saporito.",
                "price" => "16.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2012/05/ricetta-ravioli-ricotta-spinaci/jcr:content/imagePreview.img10.jpg/1542896337028.jpg",
                "name" => "Ravioli di ricotta e spinaci",
                "ingredients" => "Pasta all'uovo, ricotta, spinaci, burro, salvia, parmigiano reggiano",
                "description" => "I ravioli di ricotta e spinaci sono un piatto di pasta fresca ripiena di un delizioso mix di ricotta fresca, spinaci freschi e parmigiano reggiano. Vengono solitamente conditi con burro fuso e salvia. Sono cremosi e saporiti.",
                "price" => "13.50€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.acouplecooks.com/wp-content/uploads/2023/03/Pasta-alla-Norma-005.jpg",
                "name" => "Pasta alla Norma",
                "ingredients" => "Pasta corta, pomodori freschi, melanzane, basilico, ricotta salata, aglio",
                "description" => "La pasta alla Norma è un piatto siciliano tradizionale, composto da pasta corta condita con pomodori freschi, melanzane fritte, basilico, aglio e ricotta salata grattugiata. È un piatto estivo ricco di sapore.",
                "price" => "12.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.giallozafferano.it/images/ricette/204/20401/foto_hd/hd650x433_wm.jpg",
                "name" => "Saltimbocca alla romana",
                "ingredients" => "Fettine di vitello, prosciutto crudo, salvia, vino bianco, burro",
                "description" => "Le saltimbocca alla romana sono un piatto romano classico, composto da fettine di vitello avvolte in prosciutto crudo e foglie di salvia, poi saltate in padella con burro e vino bianco. Sono teneri e saporiti.",
                "price" => "15.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.chiarapassion.com/wp-content/uploads/2021/09/caponata-siciliana-melanzane-pomodoro-olive-capperi-sedano-basilico-aceto-zucchero-500x500.jpg",
                "name" => "Caponata siciliana",
                "ingredients" => "Melanzane, pomodori, sedano, cipolle, aceto di vino, zucchero, pinoli, uvetta",
                "description" => "La caponata siciliana è un piatto tipico della cucina siciliana, composto da melanzane fritte e condite con pomodori, sedano, cipolle, aceto di vino, zucchero, pinoli e uvetta. È agrodolce e ricca di sapori.",
                "price" => "10.50€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/a7540496-ce46-402b-af1a-42504d6dcd01/Derivates/e3901d4a-23ac-44d2-8672-5d54bc019c0b.jpg",
                "name" => "Polenta e funghi",
                "ingredients" => "Farina di mais, funghi porcini, burro, parmigiano reggiano, prezzemolo",
                "description" => "La polenta e funghi è un piatto del nord Italia, composto da polenta fatta con farina di mais e servita con funghi porcini trifolati, burro, parmigiano reggiano e prezzemolo fresco. È confortante e saporito.",
                "price" => "11.50€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2019/06/Spaghetti-alle-vongole-e-pomodorini-Ricetta-Spaghetti-con-vongole-e-pomodorini.jpg",
                "name" => "Spaghetti alle Vongole",
                "ingredients" => "Spaghetti, vongole veraci, aglio, prezzemolo, peperoncino, vino bianco",
                "description" => "Gli spaghetti alle vongole sono un piatto classico della cucina italiana, preparato con spaghetti conditi con vongole veraci fresche, aglio, prezzemolo, peperoncino e vino bianco. È un piatto fresco e saporito, perfetto per gli amanti del mare.",
                "price" => "15.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144181/hd750x421.jpg",
                "name" => "Frittura di Paranza",
                "ingredients" => "Gamberi, calamari, triglie, alici, olio per friggere, farina",
                "description" => "La frittura di paranza è un piatto tradizionale italiano, composto da una varietà di pesci di piccola taglia come gamberi, calamari, triglie e alici, passati nella farina e fritti fino a doratura. È croccante e saporito, perfetto come antipasto o piatto principale.",
                "price" => "17.50€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                "image" => "https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/03/Orata-al-cartoccio-1200x675.jpg",
                "name" => "Pesce al Cartoccio",
                "ingredients" => "Filetti di pesce misto, pomodorini, olive, capperi, aglio, prezzemolo, vino bianco",
                "description" => "Il pesce al cartoccio è un piatto italiano delicato e aromatico, preparato con filetti di pesce misto avvolti in un foglio di alluminio insieme a pomodorini, olive, capperi, aglio, prezzemolo e vino bianco. Viene cotto al forno, mantenendo tutto il sapore del pesce e degli aromi. È leggero e gustoso.",
                "price" => "16.99€",
                "visible" => true,
                'user_id' => 5,
            ],
            [
                'image' => '',
                'name' => 'Involtini primavera',
                'ingredients' => 'Sfoglie per involtini, Carote, Vino di riso, Cavolo cappuccio, Cipolle bianche, Olio di semi di arachide, Sale fino, Pepe bianco',
                'description' => "In passato venivano preparati soprattutto in occasione del Capodanno cinese, che secondo il calendario tradizionale corrisponde con l’inizio della primavera… ed ecco spiegato il loro nome: involtini primavera!",
                'price' => '9€',
                'visible' => true,
                'user_id' => 3,

            ],
            [
                'image' => '',
                'name' => 'Ravioli al vapore',
                'ingredients' => 'Maiale macinato, Cavolo cappuccio, Cipollotto fresco, Vino di riso, Salsa di soia, Sale fino, Pepe bianco',
                'description' => "Sono tipici del Capodanno cinese, come gli involtini primavera, ma vengono consumati durante tutte le festività perché la loro forma, che ricorda quella di un’antica moneta, è considerata un simbolo di buona fortuna: stiamo parlando dei ravioli cinesi al vapore!",
                'price' => '11€',
                'visible' => true,
                'user_id' => 3,

            ],
            [
                "image" => "",
                "name" => "Costine di maiale al vapore",
                "ingredients" => "Costine di maiale, salsa di soia, zenzero, aglio, cipollotti",
                "description" => "Le costine di maiale al vapore sono un piatto cinese classico, dove le costine vengono marinate con salsa di soia, zenzero e aglio, poi cotte al vapore fino a diventare tenere e saporite. Sono spesso servite con cipollotti freschi.",
                "price" => "13.50€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Baozi al vapore",
                "ingredients" => "Carne di maiale, cavolo cinese, zenzero, salsa di soia",
                "description" => "I baozi al vapore sono panini cinesi ripieni di carne di maiale aromatica, cavolo cinese e zenzero. Sono cotti al vapore fino a diventare soffici e deliziosi. Si gustano spesso come spuntino o colazione.",
                "price" => "7.49€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Pesce al curry",
                "ingredients" => "Filetto di pesce, curry in polvere, latte di cocco, peperoni, cipolle",
                "description" => "Il pesce al curry è un piatto cinese ispirato alla cucina indiana, dove filetti di pesce sono cotti in una ricca salsa al curry a base di latte di cocco, peperoni e cipolle. È un piatto aromatico e speziato.",
                "price" => "15.50€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Insalata di fagioli freddi",
                "ingredients" => "Fagioli verdi, salsa di sesamo, aglio, peperoncino, salsa di soia",
                "description" => "L'insalata di fagioli freddi è un contorno fresco e salutare della cucina cinese, preparato con fagioli verdi croccanti conditi con salsa di sesamo, aglio, peperoncino e salsa di soia. È leggero e ricco di sapori.",
                "price" => "6.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Maiale al vapore con salsa di prugne",
                "ingredients" => "Maiale, salsa di prugne, zenzero, aglio, cipollotti",
                "description" => "Il maiale al vapore con salsa di prugne è un piatto tradizionale cinese dove fette di maiale vengono cotte al vapore e servite con una salsa dolce e acidula a base di prugne, zenzero e aglio. È una delizia gustosa e salutare.",
                "price" => "14.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Pancake alla cipolla verde",
                "ingredients" => "Farina, cipolla verde, olio di sesamo, salsa di soia",
                "description" => "I pancake alla cipolla verde sono un antipasto classico della cucina cinese, preparati con strati sottili di pasta ripiegati con cipolla verde e cotti fino a diventare croccanti e dorati. Sono deliziosi e aromatici.",
                "price" => "6.50€",
                "visible" => "1",
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Congee di riso",
                "ingredients" => "Riso, brodo di pollo, zenzero, uova, cipollotti",
                "description" => "Il congee di riso è una zuppa tradizionale della colazione cinese, fatta con riso cotto lentamente in brodo di pollo con aggiunta di zenzero, uova e cipollotti. È cremoso, nutriente e confortante.",
                "price" => "8.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Tanghulu",
                "ingredients" => "Frutta mista, zucchero, bastoncini",
                "description" => "Il tanghulu è uno spuntino dolce cinese composto da frutta cristallizzata su bastoncini. Solitamente viene usata la frutta fresca, come uva o fragole, immersa in uno sciroppo di zucchero caramellato. È croccante e delizioso.",
                "price" => "4.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Pollo all'arancia",
                "ingredients" => "Pollo, scorza d'arancia, salsa di soia, zenzero, aglio",
                "description" => "Il pollo all'arancia è un piatto cinese classico caratterizzato da pezzi di pollo fritti e immersi in una salsa agrodolce aromatizzata all'arancia. È croccante e ricco di sapore.",
                "price" => "12.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Anatra alla pechinese",
                "ingredients" => "Anatra, salsa hoisin, cipollotti, pancake",
                "description" => "L'anatra alla pechinese è un piatto iconico della cucina cinese composto da fette di anatra arrosto, servite con pancake sottili, salsa hoisin e cipollotti freschi. È una delizia da condividere.",
                "price" => "18.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Zuppa agro piccante",
                "ingredients" => "Brodo di pollo, peperoncino, pepe di Sichuan, tofu, funghi, verdure",
                "description" => "La zuppa agro piccante è una zuppa cinese ricca e speziata preparata con brodo di pollo arricchito con peperoncino, pepe di Sichuan, tofu, funghi e verdure fresche. È piccante e rinfrescante.",
                "price" => "10.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Maiale in agrodolce",
                "ingredients" => "Maiale, peperoni, ananas, cipolle, salsa agrodolce",
                "description" => "Il maiale in agrodolce è un piatto cinese che combina pezzi di maiale fritti con peperoni, ananas e cipolle in una salsa agrodolce aromatica. È una combinazione equilibrata di dolce e acido.",
                "price" => "11.50€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                "image" => "",
                "name" => "Riso fritto Yangzhou",
                "ingredients" => "Riso, uova, gamberetti, piselli, carote, cipolle",
                "description" => "Il riso fritto Yangzhou è un piatto di riso cinese tradizionale fatto con riso saltato in padella con uova, gamberetti, piselli, carote e cipolle. È una pietanza gustosa e colorata.",
                "price" => "8.99€",
                "visible" => true,
                'user_id' => 3,
            ],
            [
                'image' => '',
                'name' => 'Futomaki',
                'ingredients' => 'Riso per sushi cotto, Wasabi, Alga nori, Surimi, Uova di lompo, Cetrioli, Tonno, Avocado, Salsa di soia, Zenzero sotto aceto',
                'description' => "Il futomaki è un sushi arrotolato, fatto con una foglia intera di alga nori ripiena di riso e almeno 4 ingredienti a scelta. Questa varietà di ingredienti, rende il futomaki molto colorato ed è tra i pezzi di sushi più apprezzati.",
                'price' => '6€',
                'visible' => true,
                'user_id' => 4,

            ],
            [
                'image' => '',
                'name' => 'Tempura',
                'ingredients' => 'Gamberi, Carote, Zucchine, Farina di riso, Olio di semi di girasole',
                'description' => "La tempura è uno dei piatti più conosciuti e amati della cucina del Sol Levante, nonché uno dei più richiesti nei ristoranti in giro per il mondo.",
                'price' => '8€',
                'visible' => true,
                'user_id' => 4,

            ],
            [
                "image" => "",
                "name" => "Sushi assortito",
                "ingredients" => "Riso, pesce crudo (salmone, tonno, branzino), alga nori, aceto di riso",
                "description" => "Lo sushi assortito è un piatto giapponese classico composto da una varietà di sushi, inclusi nigiri (sfere di riso con fettine di pesce crudo sopra) e maki (rotoli di riso e pesce avvolti in alga nori). È fresco e gustoso.",
                "price" => "18.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Ramen di tonkotsu",
                "ingredients" => "Brodo di ossa di maiale, noodle di frumento, maiale a fette, uovo sodo, cipollotti",
                "description" => "Il ramen di tonkotsu è una zuppa giapponese ricca e cremosa fatta con brodo di ossa di maiale e servita con noodle di frumento, maiale a fette, uovo sodo e cipollotti. È confortante e nutriente.",
                "price" => "14.50€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Tempura di gamberi",
                "ingredients" => "Gamberi, pastella leggera, olio per friggere, salsa tempura",
                "description" => "La tempura di gamberi è un piatto giapponese di gamberi ricoperti di pastella leggera e croccante, fritti in olio caldo fino a diventare dorati e croccanti. Viene spesso servita con salsa tempura per intingere.",
                "price" => "16.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Gyudon",
                "ingredients" => "Manzo a fette sottili, cipolle, salsa dashi, salsa di soia, mirin, zucchero, riso",
                "description" => "Il gyudon è una ciotola giapponese di riso servita con manzo a fette sottili cotto in una salsa dolce e salata a base di salsa dashi, salsa di soia, mirin e zucchero. È un comfort food popolare in Giappone.",
                "price" => "12.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Uramaki California",
                "ingredients" => "Riso, surimi, avocado, cetriolo, alga nori, semi di sesamo",
                "description" => "L'uramaki California è un tipo di sushi maki originario della California, composto da surimi, avocado, cetriolo avvolti in riso e alga nori, e poi ricoperti con semi di sesamo. È un sushi leggero e gustoso.",
                "price" => "13.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Okonomiyaki",
                "ingredients" => "Cavolo, pancetta, farina, uova, dashi, salsa okonomiyaki, maionese giapponese",
                "description" => "L'okonomiyaki è una specie di pancake giapponese farcito con una varietà di ingredienti come cavolo, pancetta e frutti di mare, cotto su una piastra e servito con salsa okonomiyaki e maionese giapponese. È un piatto divertente e gustoso.",
                "price" => "10.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Sashimi misto",
                "ingredients" => "Pesce crudo assortito (salmone, tonno, branzino), wasabi, salsa di soia",
                "description" => "Il sashimi misto è un piatto giapponese composto da una selezione di pesce crudo fresco, tagliato a fette sottili e servito con wasabi e salsa di soia. È una prelibatezza delicata e saporita.",
                "price" => "20.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Tonkatsu",
                "ingredients" => "Maiale impanato, cavolo fresco, salsa tonkatsu, riso",
                "description" => "Il tonkatsu è una pietanza giapponese costituita da fette di maiale impanate e fritte fino a diventare croccanti e dorate. Viene spesso servito con cavolo fresco e riso, accompagnato dalla salsa tonkatsu. È croccante e delizioso.",
                "price" => "15.50€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Yakitori",
                "ingredients" => "Spiedini di pollo, salsa tare, cipollotti",
                "description" => "Lo yakitori è un piatto giapponese di spiedini di pollo marinati e cotti alla griglia. Viene spesso servito con salsa tare, una salsa dolce e salata, e cipollotti freschi. È un piatto popolare nei bar e nelle bancarelle.",
                "price" => "9.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Unagi Don",
                "ingredients" => "Anguilla alla griglia, salsa unagi, riso",
                "description" => "L'unagi don è una ciotola di riso giapponese servita con anguilla alla griglia e glassata con salsa unagi dolce e salata. È un piatto tradizionale giapponese ricco di sapore e apprezzato per la sua morbidezza.",
                "price" => "19.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Soba noodles",
                "ingredients" => "Noodle di grano saraceno, brodo dashi, cipollotti, radice di wasabi",
                "description" => "Gli soba noodles sono una tipica pasta giapponese fatta con farina di grano saraceno, servita in brodo dashi caldo e accompagnata da cipollotti e radice di wasabi. È un piatto leggero e nutriente.",
                "price" => "11.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Oshizushi",
                "ingredients" => "Riso, pesce crudo (salmone, tonno), aceto di riso, alga nori",
                "description" => "L'oshizushi è una varietà di sushi giapponese composta da strati di riso e pesce crudo compressi in uno stampo di legno e tagliati in pezzi rettangolari. È un tipo di sushi popolare e gustoso.",
                "price" => "17.50€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Takoyaki",
                "ingredients" => "Polpo, pastella, salsa takoyaki, maionese, scaglie di bonito, alghe",
                "description" => "Il takoyaki è un piatto giapponese composto da palline di pastella ripiene di pezzi di polpo cotti su una piastra speciale. Viene spesso condito con salsa takoyaki, maionese, scaglie di bonito e alghe. È un street food popolare.",
                "price" => "8.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Miso Soup",
                "ingredients" => "Dashi, miso, alga kombu, tofu, cipollotti",
                "description" => "La zuppa di miso è una zuppa giapponese leggera e saporita fatta con brodo dashi e pasta di miso, arricchita con alga kombu, tofu a dadini e cipollotti. È un accompagnamento comune ai pasti giapponesi.",
                "price" => "5.99€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                "image" => "",
                "name" => "Onigiri",
                "ingredients" => "Riso, alga nori, ripieno (tonno, salmone, umeboshi)",
                "description" => "Gli onigiri sono palline di riso giapponesi triangolari o rotonde, spesso avvolte in alga nori e riempite con ripieni come tonno, salmone o umeboshi (prugna marinata). Sono un cibo comune per la merenda o il pranzo.",
                "price" => "4.50€",
                "visible" => true,
                'user_id' => 4,
            ],
            [
                'image' => '',
                'name' => 'Masala Dosa',
                'ingredients' => 'Patate, Semi di senape, Lenticchie, Assafetida, Foglie di curry, Zenzero, Cipolla, Foglie di coriandolo, Peperoncini verdi',
                'description' => "La tempura è uno dei piatti più conosciuti e amati della cucina del Sol Levante, nonché uno dei più richiesti nei ristoranti in giro per il mondo.",
                'price' => '11€',
                'visible' => true,
                'user_id' => 1,

            ],
            [
                'image' => '',
                'name' => 'Bhelpuri',
                'ingredients' => 'Riso soffiato, Arachidi, Ceci tostati, Cetriolo, Patate, Cipolla, Pomodoro, Chaat Masala, Curcuma',
                'description' => "Il Bhelpuri è uno snack salato, tipico della cucina indiana a base di riso soffiato, che può essere consumato col cucchiaio o raccolto su una piadina.",
                'price' => '6€',
                'visible' => true,
                'user_id' => 1,

            ],
            [
                "image" => "",
                "name" => "Pollo al burro",
                "ingredients" => "Pollo, burro, panna, pomodori, garam masala",
                "description" => "Il pollo al burro è un piatto tradizionale indiano dal sapore ricco e cremoso, preparato con pezzi di pollo marinato in una salsa di pomodoro, burro e panna. Servito con riso basmati.",
                "price" => "15.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Naan",
                "ingredients" => "Farina di grano, acqua, lievito, yogurt, sale",
                "description" => "Il Naan è un pane indiano soffice e leggero, cotto in un forno tandoor. È perfetto per accompagnare piatti come il curry o il pollo al burro.",
                "price" => "2.50€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Biryani di agnello",
                "ingredients" => "Agnello, riso basmati, garam masala, cumino, yogurt, prezzemolo",
                "description" => "Il Biryani di agnello è un piatto di riso speziato e aromatico, preparato con carne d'agnello, riso basmati e una miscela di spezie. Viene cotto lentamente per ottenere un sapore ricco e succulento.",
                "price" => "18.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Samosa",
                "ingredients" => "Patate, piselli, pasta di farina, garam masala, olio",
                "description" => "Le Samosa sono deliziose frittelle indiane ripiene di patate, piselli e spezie aromatiche. Sono croccanti all'esterno e morbide all'interno, perfette da gustare come antipasto o spuntino.",
                "price" => "3.50€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Paneer Tikka",
                "ingredients" => "Paneer, yogurt, peperoni, cipolle, garam masala",
                "description" => "Il Paneer Tikka è un antipasto indiano composto da cubetti di paneer (formaggio indiano), marinati in una miscela di yogurt e spezie, infilzati in spiedini e grigliati fino a doratura.",
                "price" => "12.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Dal Makhani",
                "ingredients" => "Lenticchie nere, fagioli, pomodori, cipolle, burro, panna, garam masala",
                "description" => "Il Dal Makhani è un piatto di lenticchie nere ricco e cremoso, cotto lentamente con una salsa di pomodoro, burro e panna. Servito con riso basmati e pane naan.",
                "price" => "14.50€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Pollo Tandoori",
                "ingredients" => "Pollo, yogurt, spezie tandoori, limone",
                "description" => "Il Pollo Tandoori è un piatto indiano in cui il pollo marinato con yogurt e spezie viene cotto in un forno tandoor, un forno indiano tradizionale a carbone. È succulento e ricco di sapore.",
                "price" => "16.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Rasgulla",
                "ingredients" => "Latte, zucchero, acqua di rosa",
                "description" => "Il Rasgulla è un dessert indiano tradizionale fatto con palline di paneer (formaggio indiano) bollite in uno sciroppo di zucchero profumato all'acqua di rosa. È dolce e rinfrescante.",
                "price" => "8.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Palak Paneer",
                "ingredients" => "Paneer, spinaci, pomodori, cipolle, garam masala, panna",
                "description" => "Il Palak Paneer è un piatto vegetariano indiano preparato con cubetti di paneer (formaggio indiano) e spinaci cotti in una salsa cremosa di pomodori, cipolle e spezie. Servito con riso basmati.",
                "price" => "13.50€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Aloo Gobi",
                "ingredients" => "Patate, cavolfiore, pomodori, cipolle, cumino, coriandolo",
                "description" => "L'Aloo Gobi è un piatto vegetariano indiano composto da patate e cavolfiore saltati in una miscela di spezie aromatiche. È semplice ma pieno di sapore.",
                "price" => "11.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Chana Masala",
                "ingredients" => "Ceci, pomodori, cipolle, zenzero, aglio, garam masala",
                "description" => "Il Chana Masala è un piatto vegetariano a base di ceci cotti in una salsa di pomodoro speziata con cipolle, zenzero e aglio. È ricco di sapori indiani autentici.",
                "price" => "11.49€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Mutter Paneer",
                "ingredients" => "Paneer, piselli, pomodori, cipolle, cumino, coriandolo",
                "description" => "Il Mutter Paneer è un piatto vegetariano indiano con paneer e piselli cotti in una salsa di pomodoro condita con spezie aromatiche come cumino e coriandolo. È delizioso e nutriente.",
                "price" => "12.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Bhindi Masala",
                "ingredients" => "Okra, pomodori, cipolle, peperoncino verde, zenzero, aglio",
                "description" => "Il Bhindi Masala è un piatto vegetariano indiano preparato con okra fresca cotta in una salsa di pomodoro piccante con cipolle, peperoncino verde, zenzero e aglio. È croccante e saporito.",
                "price" => "10.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Pav Bhaji",
                "ingredients" => "Patate, piselli, pomodori, cipolle, peperoni verdi, zenzero, pane",
                "description" => "Il Pav Bhaji è un piatto di street food indiano composto da una miscela di verdure speziate, come patate, piselli e pomodori, servita con pane tostato. È un piatto gustoso e sostanzioso.",
                "price" => "9.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                "image" => "",
                "name" => "Kheer",
                "ingredients" => "Riso, latte, zucchero, cardamomo, mandorle, pistacchi",
                "description" => "Il Kheer è un dessert di riso cremoso e dolce preparato con riso cotto lentamente nel latte aromatizzato con cardamomo, zucchero e frutta secca. È una delizia per il palato.",
                "price" => "7.99€",
                "visible" => true,
                'user_id' => 1,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/b5/pizza-margherita_dop-b54437ce.png',
                'name' => 'Margherita',
                'ingredients' => 'Pomodoro, Mozzarella, Basilico',
                'description' => "La pizza Margherita è un classico intramontabile della cucina italiana. Fu creata nel 1889 dal pizzaiolo Raffaele Esposito in onore della Regina Margherita di Savoia. La sua combinazione di sapori semplici e freschi la rende una scelta popolare per tutti i gusti.",
                'price' => '9€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/ce/pizza-mortadella-cef41c7e.webp',
                'name' => 'Mortadella',
                'ingredients' => 'Mozzarella fior di latte, Mortadella di Prato IGP Presidio Slow-Food, Burattina artigianale, Granella di pistacchio di Bronte DOP',
                'description' => "Una deliziosa pizza con mortadella di Prato IGP presidio Slow-food, burattina artigianale e mozzarella fior di latte, il tutto abbracciato da pistacchi di Bronte in grado di soddisfare anche i gusti più fini.",
                'price' => '10€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/0a/pizza-marinara-0a37a1f1.webp',
                'name' => 'Marinara',
                'ingredients' => 'Salsa di pomodoro, Origano di Pantelleria, Aglio bianco Polesano DOP',
                'description' => "Pizza marinara è una tipica pizza napoletana condita con pomodoro, aglio, origano, olio. È particolarmente apprezzata nell'Italia meridionale, dove risulta la seconda pizza preferita per gusto dopo quella con mozzarella di bufala.",
                'price' => '6€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/a4/pizza-capricciosa-2-a4c509d1.webp',
                'name' => 'Capricciosa',
                'ingredients' => 'Salsa di pomodoro, Mozzarella fior di latte, Prosciutto cotto, Funghi, Carciofi',
                'description' => "La pizza capricciosa è una pizza tipica della cucina italiana caratterizzata da un condimento di pomodoro, mozzarella fior di latte, prosciutto cotto, funghi e carciofi.

                Sebbene abbia gli stessi ingredienti della pizza alle quattro stagioni, la capricciosa presenta condimenti tutti insieme sparsi e non divisi in quattro spicchi.
                
                Risulta inventata nell'omonimo ristorante di Roma nel 1937.",
                'price' => '10€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/0a/pizza-valtellina-0aaffed6.webp',
                'name' => 'Valtelliana',
                'ingredients' => 'Salsa di pomodoro, Mozzarella fior di latte',
                'description' => 'La pizza valtellina è una pizza leggera ma allo stesso tempo ricca di gusto. Preparata con salsa di pomodoro, mozzarella fior di latte, bresaola, rucola e grana, è la soluzione ideale per tutti quelli che hanno voglia di mangiare una pizza nutriente ma allo stesso tempo leggera.',
                'price' => '10.50€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/6b/pizza-chiodini_e_sopressa-6b48aefc.webp',
                'name' => 'Chiodini e Sopressa',
                'ingredients' => 'Pomodoro, Mozzarella, Pepperoni',
                'description' => 'La pizza chiodini e sopressa è molto apprezzata per il gusto delicato e aromatico. Condita con salsa di pomodoro, mozzarella fior di latte, chiodini e sopressa, è una pizza perfetta che chi ama i gusti decisi e sapori genuini.',
                'price' => '9€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/2d/pizza-verdure-2d708cec.webp',
                'name' => 'Verdure',
                'ingredients' => 'Salsa di pomodoro, Mozzarella fior di latte, Zucchine, Melanzane, Peperoni',
                'description' => 'La pizza sfiziosa che scatena il sguardo con i suoi colori e con la combinazione delle melanzane, peperoni e zucchine abbracciando la mozzarella fior di latte e la salsa di pomodoro.',
                'price' => '10.50€',
                'visible' => true,
                'user_id' => 2,
            ],
            [
                'image' => 'https://www.pizzeriagraniantichi.it/templates/yootheme/cache/59/pizza-friarelli_e_salssicia-59a8b0a8.webp',
                'name' => 'Friarielli e Salsiccia',
                'ingredients' => 'Mozzarella fior di latte, Salsiccia, Friarielli',
                'description' => 'La pizza friarielli e salsiccia è una pizza tipica napoletana con mozzarella fior di latte, salsiccia e una nota di piccantino datto dai friarielli. Tutti questi ingredienti, messi insieme, danno un gusto deciso grazie alla loro bontà.',
                'price' => '10€',
                'visible' => true,
                'user_id' => 2,
            ],
        ];
        foreach ($foods as $food) {

            $new_food = new Food();
            $new_food->image = $food['image'];
            $new_food->name = $food['name'];
            $new_food->ingredients = $food['ingredients'];
            $new_food->description =  $food['description'];
            $new_food->price =  $food['price'];
            $new_food->visible =  $food['visible'];
            $new_food->user_id = $food['user_id'];

            $new_food->save();
        }
    }
}
