<?php

return [
    [
        'name_surname' => 'Mario Rossi',
        'address' => 'Via generica, 13, Roma (RM)',
        'phone_number' => '3332574589',
        'email' => 'mario.rossi@gmail.com',
    ],
    [
        'name_surname' => 'Jasmine Patel',
        'address' => 'Via Garibaldi, 13, Roma (RM)',
        'phone_number' => '3331112233',
        'email' => 'jasmine.patel@example.com',
    ],
    [
        'name_surname' => 'Sven Bjornsson',
        'address' => 'Via Verdi, 20, Milano (MI)',
        'phone_number' => '3334445566',
        'email' => 'sven.bjornsson@example.com',
    ],
    [
        'name_surname' => 'Laila Al-Mansoori',
        'address' => 'Via Roma, 30, Firenze (FI)',
        'phone_number' => '3337778899',
        'email' => 'laila.almansoori@example.com',
    ],
    [
        'name_surname' => 'Hiroshi Tanaka',
        'address' => 'Via Milano, 40, Napoli (NA)',
        'phone_number' => '3330001122',
        'email' => 'hiroshi.tanaka@example.com',
    ],
    [
        'name_surname' => 'Sophie Dubois',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'sophie.dubois@example.com',
    ],
    [
        'name_surname' => 'Antoine Gagnon',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'antoine.gagnon@example.com',
    ],
    [
        'name_surname' => 'Elena Ivanova',
        'address' => 'Via Manzoni, 6, Venezia (VE)',
        'phone_number' => '3339990000',
        'email' => 'elena.ivanova@example.com',
    ],
    [
        'name_surname' => 'Lars Nielsen',
        'address' => 'Via Veneto, 20, Genova (GE)',
        'phone_number' => '3332223333',
        'email' => 'lars.nielsen@example.com',
    ],
    [
        'name_surname' => 'Anastasia Sokolova',
        'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
        'phone_number' => '3337778888',
        'email' => 'anastasia.sokolova@example.com',
    ],
    [
        'name_surname' => 'Ibrahim Khan',
        'address' => 'Via della Vittoria, 15, Catania (CT)',
        'phone_number' => '3334445555',
        'email' => 'ibrahim.khan@example.com',
    ],
    [
        'name_surname' => 'Alessio Bianchini',
        'address' => 'Via Garibaldi, 13, Roma (RM)',
        'phone_number' => '3331112233',
        'email' => 'alessio.bianchini@example.com',
    ],
    [
        'name_surname' => 'Federica Montanari',
        'address' => 'Via Verdi, 20, Milano (MI)',
        'phone_number' => '3334445566',
        'email' => 'federica.montanari@example.com',
    ],
    [
        'name_surname' => 'Riccardo Abate',
        'address' => 'Via Roma, 30, Firenze (FI)',
        'phone_number' => '3337778899',
        'email' => 'riccardo.abate@example.com',
    ],
    [
        'name_surname' => 'Eleonora Fabbri',
        'address' => 'Via Milano, 40, Napoli (NA)',
        'phone_number' => '3330001122',
        'email' => 'eleonora.fabbri@example.com',
    ],
    [
        'name_surname' => 'Giacomo Barbieri',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'giacomo.barbieri@example.com',
    ],
    [
        'name_surname' => 'Angelica Carbone',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'angelica.carbone@example.com',
    ],
    [
        'name_surname' => 'Daniele Romano',
        'address' => 'Via Manzoni, 6, Venezia (VE)',
        'phone_number' => '3339990000',
        'email' => 'daniele.romano@example.com',
    ],
    [
        'name_surname' => 'Serena Del Vecchio',
        'address' => 'Via Veneto, 20, Genova (GE)',
        'phone_number' => '3332223333',
        'email' => 'serena.delvecchio@example.com',
    ],
    [
        'name_surname' => 'Gianluca Ferri',
        'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
        'phone_number' => '3337778888',
        'email' => 'gianluca.ferri@example.com',
    ],
    [
        'name_surname' => 'Arianna Pagano',
        'address' => 'Via della Vittoria, 15, Catania (CT)',
        'phone_number' => '3334445555',
        'email' => 'arianna.pagano@example.com',
    ],
    [
        'name_surname' => 'Alexander Ferrari',
        'address' => 'Via Verdi, 20, Milano (MI)',
        'phone_number' => '3334445566',
        'email' => 'alexander.ferrari@example.com',
    ],
    [
        'name_surname' => 'Maximiliano Gomez',
        'address' => 'Via Milano, 40, Napoli (NA)',
        'phone_number' => '3330001122',
        'email' => 'maximiliano.gomez@example.com',
    ],
    [
        'name_surname' => 'Olivia Lee',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'olivia.lee@example.com',
    ],
    [
        'name_surname' => 'Giovanni Chang',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'giovanni.chang@example.com',
    ],
    [
        'name_surname' => 'Liam Esposito',
        'address' => 'Via Veneto, 20, Genova (GE)',
        'phone_number' => '3332223333',
        'email' => 'liam.esposito@example.com',
    ],
    [
        'name_surname' => 'Alessia Patel',
        'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
        'phone_number' => '3337778888',
        'email' => 'alessia.patel@example.com',
    ],
    [
        'name_surname' => 'Emma Martini',
        'address' => 'Via della Vittoria, 15, Catania (CT)',
        'phone_number' => '3334445555',
        'email' => 'emma.martini@example.com',
    ],
    [
        'name_surname' => 'Francesca Smith',
        'address' => 'Via Garibaldi, 13, Roma (RM)',
        'phone_number' => '3331112233',
        'email' => 'francesca.smith@example.com',
    ],
    [
        'name_surname' => 'Lorenzo Johnson',
        'address' => 'Via Verdi, 20, Milano (MI)',
        'phone_number' => '3334445566',
        'email' => 'lorenzo.johnson@example.com',
    ],
    [
        'name_surname' => 'Giacomo Brown',
        'address' => 'Via Roma, 30, Firenze (FI)',
        'phone_number' => '3337778899',
        'email' => 'giacomo.brown@example.com',
    ],
    [
        'name_surname' => 'Antonio Esposito',
        'address' => 'Via Garibaldi, 13, Napoli (NA)',
        'phone_number' => '3331112233',
        'email' => 'antonio.esposito@example.com',
    ],
    [
        'name_surname' => 'Elisa Ricci',
        'address' => 'Via Verdi, 20, Firenze (FI)',
        'phone_number' => '3334445566',
        'email' => 'elisa.ricci@example.com',
    ],
    [
        'name_surname' => 'Luigi Russo',
        'address' => 'Via Roma, 30, Roma (RM)',
        'phone_number' => '3337778899',
        'email' => 'luigi.russo@example.com',
    ],
    [
        'name_surname' => 'Giulia Costa',
        'address' => 'Via Milano, 40, Milano (MI)',
        'phone_number' => '3330001122',
        'email' => 'giulia.costa@example.com',
    ],
    [
        'name_surname' => 'Giovanni Ferri',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'giovanni.ferri@example.com',
    ],
    [
        'name_surname' => 'Francesca Martini',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'francesca.martini@example.com',
    ],
    [
        'name_surname' => 'Paolo Conti',
        'address' => 'Via Manzoni, 6, Genova (GE)',
        'phone_number' => '3339990000',
        'email' => 'paolo.conti@example.com',
    ],
    [
        'name_surname' => 'Elena Gatti',
        'address' => 'Via Veneto, 20, Palermo (PA)',
        'phone_number' => '3332223333',
        'email' => 'elena.gatti@example.com',
    ],
    [
        'name_surname' => 'Marco Lombardi',
        'address' => 'Corso Vittorio Emanuele, 25, Catania (CT)',
        'phone_number' => '3337778888',
        'email' => 'marco.lombardi@example.com',
    ],
    [
        'name_surname' => 'Francesca Caruso',
        'address' => 'Via della Vittoria, 15, Venezia (VE)',
        'phone_number' => '3334445555',
        'email' => 'francesca.caruso@example.com',
    ],
    [
        'name_surname' => 'Emma Morelli',
        'address' => 'Via Garibaldi, 13, Roma (RM)',
        'phone_number' => '3331112233',
        'email' => 'emma.morelli@example.com',
    ],
    [
        'name_surname' => 'Liam Marini',
        'address' => 'Via Verdi, 20, Milano (MI)',
        'phone_number' => '3334445566',
        'email' => 'liam.marini@example.com',
    ],
    [
        'name_surname' => 'Sophia De Santis',
        'address' => 'Via Roma, 30, Firenze (FI)',
        'phone_number' => '3337778899',
        'email' => 'sophia.desantis@example.com',
    ],
    [
        'name_surname' => 'Noah Greco',
        'address' => 'Via Milano, 40, Napoli (NA)',
        'phone_number' => '3330001122',
        'email' => 'noah.greco@example.com',
    ],
    [
        'name_surname' => 'Olivia Ferrari',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'olivia.ferrari@example.com',
    ],
    [
        'name_surname' => 'William Lombardi',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'william.lombardi@example.com',
    ],
    [
        'name_surname' => 'Ava Romano',
        'address' => 'Via Manzoni, 6, Venezia (VE)',
        'phone_number' => '3339990000',
        'email' => 'ava.romano@example.com',
    ],
    [
        'name_surname' => 'Mia Colombo',
        'address' => 'Via Veneto, 20, Genova (GE)',
        'phone_number' => '3332223333',
        'email' => 'mia.colombo@example.com',
    ],
    [
        'name_surname' => 'James Russo',
        'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
        'phone_number' => '3337778888',
        'email' => 'james.russo@example.com',
    ],
    [
        'name_surname' => 'Isabella Rinaldi',
        'address' => 'Via della Vittoria, 15, Catania (CT)',
        'phone_number' => '3334445555',
        'email' => 'isabella.rinaldi@example.com',
    ],
    [
        'name_surname' => 'Simone Marchetti',
        'address' => 'Via Garibaldi, 13, Roma (RM)',
        'phone_number' => '3331112233',
        'email' => 'simone.marchetti@example.com',
    ],
    [
        'name_surname' => 'Valentina Ferrari',
        'address' => 'Via Verdi, 20, Milano (MI)',
        'phone_number' => '3334445566',
        'email' => 'valentina.ferrari@example.com',
    ],
    [
        'name_surname' => 'Luca Galli',
        'address' => 'Via Roma, 30, Firenze (FI)',
        'phone_number' => '3337778899',
        'email' => 'luca.galli@example.com',
    ],
    [
        'name_surname' => 'Martina Rizzo',
        'address' => 'Via Milano, 40, Napoli (NA)',
        'phone_number' => '3330001122',
        'email' => 'martina.rizzo@example.com',
    ],
    [
        'name_surname' => 'Andrea De Luca',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'andrea.deluca@example.com',
    ],
    [
        'name_surname' => 'Silvia Bianchi',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'silvia.bianchi@example.com',
    ],
    [
        'name_surname' => 'Giovanni Barbieri',
        'address' => 'Via Manzoni, 6, Venezia (VE)',
        'phone_number' => '3339990000',
        'email' => 'giovanni.barbieri@example.com',
    ],
    [
        'name_surname' => 'Federica Colombo',
        'address' => 'Via Veneto, 20, Genova (GE)',
        'phone_number' => '3332223333',
        'email' => 'federica.colombo@example.com',
    ],
    [
        'name_surname' => 'Marco Rossetti',
        'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
        'phone_number' => '3337778888',
        'email' => 'marco.rossetti@example.com',
    ],
    [
        'name_surname' => 'Chiara Marini',
        'address' => 'Via della Vittoria, 15, Catania (CT)',
        'phone_number' => '3334445555',
        'email' => 'chiara.marini@example.com',
    ],
    [
        'name_surname' => 'Alessia Williams',
        'address' => 'Via Milano, 40, Napoli (NA)',
        'phone_number' => '3330001122',
        'email' => 'alessia.williams@example.com',
    ],
    [
        'name_surname' => 'Matteo Taylor',
        'address' => 'Via Torino, 50, Torino (TO)',
        'phone_number' => '3333334455',
        'email' => 'matteo.taylor@example.com',
    ],
    [
        'name_surname' => 'Sara Davis',
        'address' => 'Via dei Mille, 5, Bologna (BO)',
        'phone_number' => '3336667788',
        'email' => 'sara.davis@example.com',
    ],
    [
        'name_surname' => 'Andrea Martinez',
        'address' => 'Via Manzoni, 6, Venezia (VE)',
        'phone_number' => '3339990000',
        'email' => 'andrea.martinez@example.com',
    ],
    [
        'name_surname' => 'Giulia Rodriguez',
        'address' => 'Via Veneto, 20, Genova (GE)',
        'phone_number' => '3332223333',
        'email' => 'giulia.rodriguez@example.com',
    ],
    [
        'name_surname' => 'Marco Lopez',
        'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
        'phone_number' => '3337778888',
        'email' => 'marco.lopez@example.com',
    ],
    [
        'name_surname' => 'Elisa Garcia',
        'address' => 'Via della Vittoria, 15, Catania (CT)',
        'phone_number' => '3334445555',
        'email' => 'elisa.garcia@example.com',
    ],

];
