<?php
return
    [
        [
            "message" => "Buonasera, vorrei la pizza diavola bel cotta",
            "payment_status" => "1",
            "order_date" => "2018-07-23",
            "total_price" => 54.30,
            'name_surname' => 'Mario Rossi',
            'address' => 'Via generica, 13, Roma (RM)',
            'phone_number' => '3332574589',
            'email' => 'mario.rossi@gmail.com',
        ],
        [
            "message" => "Salve vorrei l'uovo ben cotto",
            "payment_status" => "1",
            "order_date" => "2022-10-22",
            "total_price" => 112.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Spaghetti senza pepe",
            "payment_status" => "1",
            "order_date" => "2022-09-28",
            "total_price" => 28.75,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Entrare nell'interno b, 3° piano",
            "payment_status" => "1",
            "order_date" => "2022-08-21",
            "total_price" => 24.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Chiamare all'arrivo",
            "payment_status" => "1",
            "order_date" => "2022-11-02",
            "total_price" => 31.20,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2018-08-09",
            "total_price" => 82.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2019-03-17",
            "total_price" => 27.60,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Ciao, potresti per favore aggiungere più salsa piccante",
            "payment_status" => "1",
            "order_date" => "2022-07-17",
            "total_price" => 16.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "No basilico",
            "payment_status" => "1",
            "order_date" => "2022-12-09",
            "total_price" => 68.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2022-06-30",
            "total_price" => 28.60,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Sono al lavoro, puoi consegnare l'ordine presso la portineria del mio ufficio? Grazie mille!",
            "payment_status" => "1",
            "order_date" => "2022-05-12",
            "total_price" => 54.40,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Per favore, assicuratevi che l'insalata non contenga noci. Sono allergico. Grazie per la tua attenzione!",
            "payment_status" => "1",
            "order_date" => "2022-04-03",
            "total_price" => 19.75,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Posso avere dell'aglio extra? Grazie!",
            "payment_status" => "1",
            "order_date" => "2022-03-21",
            "total_price" => 29.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Aggiungete un po' di peperoncino in più sulla pizza, per favore.",
            "payment_status" => "1",
            "order_date" => "2018-08-15",
            "total_price" => 49.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Per favore, fate attenzione a non mettere troppo formaggio sulla pizza. Grazie!",
            "payment_status" => "1",
            "order_date" => "2019-05-02",
            "total_price" => 32.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2021-01-03",
            "total_price" => 31.40,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Mi trovo al piano terra dell'edificio. Chiamate quando siete qui.",
            "payment_status" => "1",
            "order_date" => "2020-10-19",
            "total_price" => 27.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Potete aggiungere più olive sulla pizza Grazie mille!",
            "payment_status" => "1",
            "order_date" => "2021-11-08",
            "total_price" => 41.20,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2022-03-30",
            "total_price" => 38.60,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2020-10-05",
            "total_price" => 30.10,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Per favore, assicuratevi che la pizza non sia troppo condita. Grazie!",
            "payment_status" => "1",
            "order_date" => "2022-09-12",
            "total_price" => 23.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2020-04-15",
            "total_price" => 125.30,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2022-11-22",
            "total_price" => 38.20,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "La consegna deve essere effettuata entro le 19 =>30. Grazie per la vostra comprensione!",
            "payment_status" => "1",
            "order_date" => "2023-07-04",
            "total_price" => 45.70,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Potete includere più utensili nella confezione? Ne servono almeno due. Grazie!",
            "payment_status" => "1",
            "order_date" => "2023-11-21",
            "total_price" => 29.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Mi scuso per l'errore nell'indirizzo. L'indirizzo corretto è Via Roma 123. Grazie per la comprensione!",
            "payment_status" => "1",
            "order_date" => "2024-01-15",
            "total_price" => 36.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2018-12-12",
            "total_price" => 20.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2019-07-28",
            "total_price" => 17.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Per favore, consegnate l'ordine al mio ufficio al terzo piano. Grazie!",
            "payment_status" => "1",
            "order_date" => "2024-05-29",
            "total_price" => 52.40,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Per favore, chiamate quando siete vicini, grazie!",
            "payment_status" => "1",
            "order_date" => "2018-09-15",
            "total_price" => 49.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Consegna senza contatto",
            "payment_status" => "1",
            "order_date" => "2019-02-28",
            "total_price" => 42.20,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Il cancello posteriore è aperto, potete consegnare là. Grazie!",
            "payment_status" => "1",
            "order_date" => "2020-11-12",
            "total_price" => 27.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Sono allergico ai latticini, per favore fare attenzione. Grazie!",
            "payment_status" => "1",
            "order_date" => "2021-06-05",
            "total_price" => 38.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Si prega di consegnare entro le 18 =>00, grazie!",
            "payment_status" => "1",
            "order_date" => "2018-04-19",
            "total_price" => 16.70,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Il mio cane è in giardino, per favore non suonare il campanello. Grazie!",
            "payment_status" => "1",
            "order_date" => "2019-09-20",
            "total_price" => 21.40,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "La casa è di fronte al parco, non sarà difficile. Grazie!",
            "payment_status" => "1",
            "order_date" => "2020-05-08",
            "total_price" => 32.60,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2021-12-30",
            "total_price" => 26.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2018-10-17",
            "total_price" => 18.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "L'ingresso è sulla strada laterale, grazie!",
            "payment_status" => "1",
            "order_date" => "2019-07-02",
            "total_price" => 59.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Sono al lavoro, potete lasciare l'ordine al portone principale? Grazie!",
            "payment_status" => "1",
            "order_date" => "2020-03-14",
            "total_price" => 24.70,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "La consegna deve essere discreta, per favore non fare troppo rumore. Grazie!",
            "payment_status" => "1",
            "order_date" => "2021-11-05",
            "total_price" => 119.20,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Sono in riunione fino alle 13 =>00, per favore consegnate dopo. Grazie!",
            "payment_status" => "1",
            "order_date" => "2018-08-21",
            "total_price" => 22.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "",
            "payment_status" => "1",
            "order_date" => "2019-04-18",
            "total_price" => 134.80,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Non suonate il campanello, il bambino dorme. Grazie!",
            "payment_status" => "1",
            "order_date" => "2020-12-03",
            "total_price" => 28.60,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "No aglio, per favore. Grazie!",
            "payment_status" => "1",
            "order_date" => "2021-07-17",
            "total_price" => 8.90,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        // PASQUALE ORDERS
        [
            "message" => "Pizza margherita con mozzarella di bufala e basilico fresco",
            "payment_status" => 1,
            "order_date" => "2023-05-12",
            "total_price" => 12.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Buonasera, vorrei la pizza diavola bel cotta",
            "payment_status" => 1,
            "order_date" => "2023-02-26",
            "total_price" => 54.30,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Due pizze margherita, una grande e una piccola, con patatine fritte",
            "payment_status" => 1,
            "order_date" => "2021-07-20",
            "total_price" => 22.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Pizza diavola con extra peperoncino e una birra Moretti",
            "payment_status" => 1,
            "order_date" => "2020-12-31",
            "total_price" => 15.00,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Pizza ortolana con verdure di stagione e impasto integrale",
            "payment_status" => 1,
            "order_date" => "2024-01-01",
            "total_price" => 12.00,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Vorrei una pizza capricciosa e una hawaiana, per favore",
            "payment_status" => 1,
            "order_date" => "2023-08-15",
            "total_price" => 20.0,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Buonasera, vorrei la pizza margherita con mozzarella di bufala",
            "payment_status" => 1,
            "order_date" => "2022-03-08",
            "total_price" => 14.00,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Pizza capricciosa con funghi",
            "payment_status" => 1,
            "order_date" => "2023-11-14",
            "total_price" => 13.50,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Vorrei una pizza diavola e una margherita",
            "payment_status" => 1,
            "order_date" => "2022-05-03",
            "total_price" => 18.00,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Pizza margherita con doppia mozzarella",
            "payment_status" => 1,
            "order_date" => "2023-05-12",
            "total_price" => 11.00,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Due pizze capricciosa, una con impasto senza glutine",
            "payment_status" => 1,
            "order_date" => "2022-11-01",
            "total_price" => 27.00,
            'name_surname' => 'Marco Lombardi',
            'address' => 'Corso Vittorio Emanuele, 25, Catania (CT)',
            'phone_number' => '3337778888',
            'email' => 'marco.lombardi@example.com',
        ],
        [
            "message" => "Pizza hawaiana con extra ananas",
            "payment_status" => 1,
            "order_date" => "2020-08-15",
            "total_price" => 10.50,
            'name_surname' => 'Francesca Caruso',
            'address' => 'Via della Vittoria, 15, Venezia (VE)',
            'phone_number' => '3334445555',
            'email' => 'francesca.caruso@example.com',
        ],
        [
            "message" => "Pizza ortolana con verdure grigliate",
            "payment_status" => 1,
            "order_date" => "2024-02-26",
            "total_price" => 13.00,
            'name_surname' => 'Emma Morelli',
            'address' => 'Via Garibaldi, 13, Roma (RM)',
            'phone_number' => '3331112233',
            'email' => 'emma.morelli@example.com',
        ],
        [
            "message" => "Quattro pizze margherita, una grande e tre piccole",
            "payment_status" => 1,
            "order_date" => "2023-10-31",
            "total_price" => 35.00,
            'name_surname' => 'Liam Marini',
            'address' => 'Via Verdi, 20, Milano (MI)',
            'phone_number' => '3334445566',
            'email' => 'liam.marini@example.com',
        ],
        [
            "message" => "Pizza diavola con salame piccante",
            "payment_status" => 1,
            "order_date" => "2022-04-01",
            "total_price" => 12.50,
            'name_surname' => 'Sophia De Santis',
            'address' => 'Via Roma, 30, Firenze (FI)',
            'phone_number' => '3337778899',
            'email' => 'sophia.desantis@example.com',
        ],
        [
            "message" => "Pizza capricciosa con funghi e olive nere",
            "payment_status" => 1,
            "order_date" => "2020-12-25",
            "total_price" => 14.00,
            'name_surname' => 'Noah Greco',
            'address' => 'Via Milano, 40, Napoli (NA)',
            'phone_number' => '3330001122',
            'email' => 'noah.greco@example.com',
        ],
        [
            "message" => "Due pizze margherita e una coca cola",
            "payment_status" => 1,
            "order_date" => "2024-01-01",
            "total_price" => 20.00,
            'name_surname' => 'Olivia Ferrari',
            'address' => 'Via Torino, 50, Torino (TO)',
            'phone_number' => '3333334455',
            'email' => 'olivia.ferrari@example.com',
        ],
        [
            "message" => "Pizza ortolana con pesto alla genovese",
            "payment_status" => 1,
            "order_date" => "2023-08-15",
            "total_price" => 15.00,
            'name_surname' => 'William Lombardi',
            'address' => 'Via dei Mille, 5, Bologna (BO)',
            'phone_number' => '3336667788',
            'email' => 'william.lombardi@example.com',
        ],
        [
            "message" => "Pizza hawaiana con prosciutto cotto e ananas",
            "payment_status" => 1,
            "order_date" => "2022-03-08",
            "total_price" => 11.50,
            'name_surname' => 'Ava Romano',
            'address' => 'Via Manzoni, 6, Venezia (VE)',
            'phone_number' => '3339990000',
            'email' => 'ava.romano@example.com',
        ],
        [
            "message" => "Buonasera, vorrei la pizza diavola bel cotta",
            "payment_status" => 1,
            "order_date" => "2023-02-26",
            "total_price" => 54.30,
            'name_surname' => 'Mia Colombo',
            'address' => 'Via Veneto, 20, Genova (GE)',
            'phone_number' => '3332223333',
            'email' => 'mia.colombo@example.com',
        ],
        [
            "message" => "Due pizze margherita, una grande e una piccola, con patatine fritte",
            "payment_status" => 1,
            "order_date" => "2021-07-20",
            "total_price" => 22.50,
            'name_surname' => 'James Russo',
            'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
            'phone_number' => '3337778888',
            'email' => 'james.russo@example.com',
        ],
        [
            "message" => "Pizza diavola con extra peperoncino e una birra Moretti",
            "payment_status" => 1,
            "order_date" => "2020-12-31",
            "total_price" => 15.00,
            'name_surname' => 'Isabella Rinaldi',
            'address' => 'Via della Vittoria, 15, Catania (CT)',
            'phone_number' => '3334445555',
            'email' => 'isabella.rinaldi@example.com',
        ],
        [
            "message" => "Pizza ortolana con verdure di stagione e impasto integrale",
            "payment_status" => 1,
            "order_date" => "2024-01-01",
            "total_price" => 12.00,
            'name_surname' => 'Simone Marchetti',
            'address' => 'Via Garibaldi, 13, Roma (RM)',
            'phone_number' => '3331112233',
            'email' => 'simone.marchetti@example.com',
        ],
        [
            "message" => "Vorrei una pizza capricciosa e una hawaiana, per favore",
            "payment_status" => 1,
            "order_date" => "2023-08-15",
            "total_price" => 20.00,
            'name_surname' => 'Valentina Ferrari',
            'address' => 'Via Verdi, 20, Milano (MI)',
            'phone_number' => '3334445566',
            'email' => 'valentina.ferrari@example.com',
        ],
        [
            "message" => "Buonasera, vorrei la pizza margherita con mozzarella di bufala",
            "payment_status" => 1,
            "order_date" => "2022-03-08",
            "total_price" => 14.00,
            'name_surname' => 'Luca Galli',
            'address' => 'Via Roma, 30, Firenze (FI)',
            'phone_number' => '3337778899',
            'email' => 'luca.galli@example.com',
        ],
        [
            "message" => "Pizza capricciosa con funghi",
            "payment_status" => 1,
            "order_date" => "2023-11-14",
            "total_price" => 13.50,
            'name_surname' => 'Martina Rizzo',
            'address' => 'Via Milano, 40, Napoli (NA)',
            'phone_number' => '3330001122',
            'email' => 'martina.rizzo@example.com',
        ],
        [
            "message" => "Vorrei una pizza diavola e una margherita",
            "payment_status" => 1,
            "order_date" => "2022-05-03",
            "total_price" => 18.00,
            "name_surname" => "",
            "address" => "",
            "phone_number" => "",
            "email" => ""
        ],
        [
            "message" => "Pizza margherita con basilico fresco",
            "payment_status" => 1,
            "order_date" => "2023-04-25",
            "total_price" => 10.00,
            'name_surname' => 'Andrea De Luca',
            'address' => 'Via Torino, 50, Torino (TO)',
            'phone_number' => '3333334455',
            'email' => 'andrea.deluca@example.com',
        ],
        [
            "message" => "Due pizze capricciosa, una con bordo ripieno di ricotta",
            "payment_status" => 1,
            "order_date" => "2022-10-05",
            "total_price" => 30.00,
            'name_surname' => 'Silvia Bianchi',
            'address' => 'Via dei Mille, 5, Bologna (BO)',
            'phone_number' => '3336667788',
            'email' => 'silvia.bianchi@example.com',
        ],
        [
            "message" => "Pizza hawaiana con salsa barbecue",
            "payment_status" => 1,
            "order_date" => "2020-09-10",
            "total_price" => 11.00,
            'name_surname' => 'Giovanni Barbieri',
            'address' => 'Via Manzoni, 6, Venezia (VE)',
            'phone_number' => '3339990000',
            'email' => 'giovanni.barbieri@example.com',
        ],
        [
            "message" => "Pizza ortolana con pomodorini pachino e mozzarella di bufala",
            "payment_status" => 1,
            "order_date" => "2024-03-14",
            "total_price" => 14.50,
            'name_surname' => 'Federica Colombo',
            'address' => 'Via Veneto, 20, Genova (GE)',
            'phone_number' => '3332223333',
            'email' => 'federica.colombo@example.com',
        ],
        [
            "message" => "Quattro pizze margherita e una coca cola zero",
            "payment_status" => 1,
            "order_date" => "2023-11-22",
            "total_price" => 36.00,
            'name_surname' => 'Marco Rossetti',
            'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
            'phone_number' => '3337778888',
            'email' => 'marco.rossetti@example.com',
        ],
        [
            "message" => "Pizza diavola con salsiccia piccante",
            "payment_status" => 1,
            "order_date" => "2022-05-12",
            "total_price" => 13.00,
            'name_surname' => 'Chiara Marini',
            'address' => 'Via della Vittoria, 15, Catania (CT)',
            'phone_number' => '3334445555',
            'email' => 'chiara.marini@example.com',
        ],
        [
            "message" => "Pizza capricciosa con funghi porcini e olive nere",
            "payment_status" => 1,
            "order_date" => "2020-12-24",
            "total_price" => 15.50,
            'name_surname' => 'Alessia Williams',
            'address' => 'Via Milano, 40, Napoli (NA)',
            'phone_number' => '3330001122',
            'email' => 'alessia.williams@example.com',
        ],
        [
            "message" => "Due pizze margherita e una birra Moretti analcolica",
            "payment_status" => 1,
            "order_date" => "2024-02-02",
            "total_price" => 21.00,
            'name_surname' => 'Matteo Taylor',
            'address' => 'Via Torino, 50, Torino (TO)',
            'phone_number' => '3333334455',
            'email' => 'matteo.taylor@example.com',
        ],
        [
            "message" => "Pizza ortolana con pesto alla genovese e ricotta",
            "payment_status" => 1,
            "order_date" => "2023-09-19",
            "total_price" => 16.00,
            'name_surname' => 'Sara Davis',
            'address' => 'Via dei Mille, 5, Bologna (BO)',
            'phone_number' => '3336667788',
            'email' => 'sara.davis@example.com',
        ],
        [
            "message" => "Pizza hawaiana con prosciutto cotto, ananas e pancetta",
            "payment_status" => 1,
            "order_date" => "2022-04-07",
            "total_price" => 12.00,
            'name_surname' => 'Andrea Martinez',
            'address' => 'Via Manzoni, 6, Venezia (VE)',
            'phone_number' => '3339990000',
            'email' => 'andrea.martinez@example.com',
        ],
        [
            "message" => "Buonasera, vorrei la pizza margherita con pomodoro pachino",
            "payment_status" => 1,
            "order_date" => "2023-03-20",
            "total_price" => 54.30,
            'name_surname' => 'Giulia Rodriguez',
            'address' => 'Via Veneto, 20, Genova (GE)',
            'phone_number' => '3332223333',
            'email' => 'giulia.rodriguez@example.com',
        ],
        [
            "message" => "Due pizze capricciosa, una grande e una piccola, con patatine fritte e una coca cola",
            "payment_status" => 1,
            "order_date" => "2021-08-15",
            "total_price" => 25.00,
            'name_surname' => 'Marco Lopez',
            'address' => 'Corso Vittorio Emanuele, 25, Palermo (PA)',
            'phone_number' => '3337778888',
            'email' => 'marco.lopez@example.com',
        ],
        [
            "message" => "Pizza diavola con extra peperoncino e una birra Messina",
            "payment_status" => 1,
            "order_date" => "2020-11-01",
            "total_price" => 16.00,
            'name_surname' => 'Elisa Garcia',
            'address' => 'Via della Vittoria, 15, Catania (CT)',
            'phone_number' => '3334445555',
            'email' => 'elisa.garcia@example.com',

        ],

    ];
