<?php
return
[
    [
        "message" => "Buonasera, vorrei la pizza diavola bel cotta",
        "payment_status" => "1",
        "order_date" => "2018-07-23",
        "total_price" => "54.30€",
    ],
    [
        "message" => "Salve vorrei l'uovo ben cotto",
        "payment_status" => "1",
        "order_date" => "2022-10-22",
        "total_price" => "112.50€",
    ],
    [
        "message" => "Spaghetti senza pepe",
        "payment_status" => "1",
        "order_date" => "2022-09-28",
        "total_price" => "28.75€",
    ],
    [
        "message" => "Entrare nell'interno b, 3° piano",
        "payment_status" => "1",
        "order_date" => "2022-08-21",
        "total_price" => "24.90€",
    ],
    [
        "message" => "Chiamare all'arrivo",
        "payment_status" => "1",
        "order_date" => "2022-11-02",
        "total_price" => "31.20€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2018-08-09",
        "total_price" => "82.90€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2019-03-17",
        "total_price" => "27.60€",
    ],   
    [
        "message" => "Ciao, potresti per favore aggiungere più salsa piccante",
        "payment_status" => "1",
        "order_date" => "2022-07-17",
        "total_price" => "16.80€",
    ],
    [
        "message" => "No basilico",
        "payment_status" => "1",
        "order_date" => "2022-12-09",
        "total_price" => "68.90€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2022-06-30",
        "total_price" => "28.60€",
    ],
    [
        "message" => "Sono al lavoro, puoi consegnare l'ordine presso la portineria del mio ufficio? Grazie mille!",
        "payment_status" => "1",
        "order_date" => "2022-05-12",
        "total_price" => "54.40€",
    ],
    [
        "message" => "Per favore, assicuratevi che l'insalata non contenga noci. Sono allergico. Grazie per la tua attenzione!",
        "payment_status" => "1",
        "order_date" => "2022-04-03",
        "total_price" => "19.75€",
    ],
    [
        "message" => "Posso avere dell'aglio extra? Grazie!",
        "payment_status" => "1",
        "order_date" => "2022-03-21",
        "total_price" => "29.50€",
    ],
    [
        "message" => "Aggiungete un po' di peperoncino in più sulla pizza, per favore.",
        "payment_status" => "1",
        "order_date" => "2018-08-15",
        "total_price" => "49.90€",
    ],
    [
        "message" => "Per favore, fate attenzione a non mettere troppo formaggio sulla pizza. Grazie!",
        "payment_status" => "1",
        "order_date" => "2019-05-02",
        "total_price" => "32.50€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2021-01-03",
        "total_price" => "31.40€",
    ],
    [
        "message" => "Mi trovo al piano terra dell'edificio. Chiamate quando siete qui.",
        "payment_status" => "1",
        "order_date" => "2020-10-19",
        "total_price" => "27.80€",
    ],
    [
        "message" => "Potete aggiungere più olive sulla pizza Grazie mille!",
        "payment_status" => "1",
        "order_date" => "2021-11-08",
        "total_price" => "41.20€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2022-03-30",
        "total_price" => "38.60€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2020-10-05",
        "total_price" => "30.10€",
    ],
    [
        "message" => "Per favore, assicuratevi che la pizza non sia troppo condita. Grazie!",
        "payment_status" => "1",
        "order_date" => "2022-09-12",
        "total_price" => "23.90€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2020-04-15",
        "total_price" => "125.30€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2022-11-22",
        "total_price" => "38.20€",
    ],
    [
        "message" => "La consegna deve essere effettuata entro le 19:30. Grazie per la vostra comprensione!",
        "payment_status" => "1",
        "order_date" => "2023-07-04",
        "total_price" => "45.70€",
    ],
    [
        "message" => "Potete includere più utensili nella confezione? Ne servono almeno due. Grazie!",
        "payment_status" => "1",
        "order_date" => "2023-11-21",
        "total_price" => "29.50€",
    ],
    [
        "message" => "Mi scuso per l'errore nell'indirizzo. L'indirizzo corretto è Via Roma 123. Grazie per la comprensione!",
        "payment_status" => "1",
        "order_date" => "2024-01-15",
        "total_price" => "36.80€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2018-12-12",
        "total_price" => "20.50€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2019-07-28",
        "total_price" => "17.80€",
    ],
    [
        "message" => "Per favore, consegnate l'ordine al mio ufficio al terzo piano. Grazie!",
        "payment_status" => "1",
        "order_date" => "2024-05-29",
        "total_price" => "52.40€",
    ],
    [
        "message" => "Per favore, chiamate quando siete vicini, grazie!",
        "payment_status" => "1",
        "order_date" => "2018-09-15",
        "total_price" => "49.50€",
    ],
    [
        "message" => "Consegna senza contatto",
        "payment_status" => "1",
        "order_date" => "2019-02-28",
        "total_price" => "42.20€",
    ],
    [
        "message" => "Il cancello posteriore è aperto, potete consegnare là. Grazie!",
        "payment_status" => "1",
        "order_date" => "2020-11-12",
        "total_price" => "27.80€",
    ],
    [
        "message" => "Sono allergico ai latticini, per favore fare attenzione. Grazie!",
        "payment_status" => "1",
        "order_date" => "2021-06-05",
        "total_price" => "38.90€",
    ],
    [
        "message" => "Si prega di consegnare entro le 18:00, grazie!",
        "payment_status" => "1",
        "order_date" => "2018-04-19",
        "total_price" => "16.70€",
    ],
    [
        "message" => "Il mio cane è in giardino, per favore non suonare il campanello. Grazie!",
        "payment_status" => "1",
        "order_date" => "2019-09-20",
        "total_price" => "21.40€",
    ],
    [
        "message" => "La casa è di fronte al parco, non sarà difficile. Grazie!",
        "payment_status" => "1",
        "order_date" => "2020-05-08",
        "total_price" => "32.60€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2021-12-30",
        "total_price" => "26.80€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2018-10-17",
        "total_price" => "18.50€",
    ],
    [
        "message" => "L'ingresso è sulla strada laterale, grazie!",
        "payment_status" => "1",
        "order_date" => "2019-07-02",
        "total_price" => "59.90€",
    ],
    [
        "message" => "Sono al lavoro, potete lasciare l'ordine al portone principale? Grazie!",
        "payment_status" => "1",
        "order_date" => "2020-03-14",
        "total_price" => "24.70€",
    ],
    [
        "message" => "La consegna deve essere discreta, per favore non fare troppo rumore. Grazie!",
        "payment_status" => "1",
        "order_date" => "2021-11-05",
        "total_price" => "119.20€",
    ],
    [
        "message" => "Sono in riunione fino alle 13:00, per favore consegnate dopo. Grazie!",
        "payment_status" => "1",
        "order_date" => "2018-08-21",
        "total_price" => "22.90€",
    ],
    [
        "message" => "",
        "payment_status" => "1",
        "order_date" => "2019-04-18",
        "total_price" => "134.80€",
    ],
    [
        "message" => "Non suonate il campanello, il bambino dorme. Grazie!",
        "payment_status" => "1",
        "order_date" => "2020-12-03",
        "total_price" => "28.60€",
    ],
    [
        "message" => "No aglio, per favore. Grazie!",
        "payment_status" => "1",
        "order_date" => "2021-07-17",
        "total_price" => "8.90€"
    ]
];